[2023-05-26T07:19:46.553+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=manual__2023-05-26T07:19:36.288103+00:00/task_id=csv_to_parquet_2015 permission to 509
[2023-05-26T07:19:46.653+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=manual__2023-05-26T07:19:36.288103+00:00/task_id=csv_to_parquet_2015 permission to 509
[2023-05-26T07:19:46.721+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.csv_to_parquet_2015 manual__2023-05-26T07:19:36.288103+00:00 [queued]>
[2023-05-26T07:19:46.744+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.csv_to_parquet_2015 manual__2023-05-26T07:19:36.288103+00:00 [queued]>
[2023-05-26T07:19:46.746+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-26T07:19:46.783+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): csv_to_parquet_2015> on 2023-05-26 07:19:36.288103+00:00
[2023-05-26T07:19:46.795+0000] {standard_task_runner.py:57} INFO - Started process 230 to run task
[2023-05-26T07:19:46.804+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'csv_to_parquet_2015', 'manual__2023-05-26T07:19:36.288103+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_gcs_dag.py', '--cfg-path', '/tmp/tmpw9r80t09']
[2023-05-26T07:19:46.814+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask csv_to_parquet_2015
[2023-05-26T07:19:46.937+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=manual__2023-05-26T07:19:36.288103+00:00/task_id=csv_to_parquet_2015 permission to 509
[2023-05-26T07:19:46.958+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_gcs_dag.csv_to_parquet_2015 manual__2023-05-26T07:19:36.288103+00:00 [running]> on host 71de5723b7f9
[2023-05-26T07:19:47.138+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='csv_to_parquet_2015' AIRFLOW_CTX_EXECUTION_DATE='2023-05-26T07:19:36.288103+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-26T07:19:36.288103+00:00'
[2023-05-26T07:19:47.149+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_gcs_dag.py", line 31, in convert_csv_to_parquet
    df = pd.read_csv(f"{path_to_local_home}/{file_csv}")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2023-05-26T07:19:47.182+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=csv_to_parquet_2015, execution_date=20230526T071936, start_date=20230526T071946, end_date=20230526T071947
[2023-05-26T07:19:47.201+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 29 for task csv_to_parquet_2015 (No columns to parse from file; 230)
[2023-05-26T07:19:47.257+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-26T07:19:47.298+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
